"""update ActivityLog fields

Revision ID: 26f00b9dc19e
Revises: 
Create Date: 2025-11-15 06:26:35.070106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26f00b9dc19e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('image', sa.String(length=255), nullable=True))
        batch_op.alter_column('employee_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('location')
        batch_op.drop_column('photo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=255), nullable=True))
        batch_op.alter_column('employee_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('image')
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    # ### end Alembic commands ###
